#!/usr/bin/env python3
"""
daily_digest.py — "plan the day" (morning) / "recap the day" (evening)
text, generated by reading the project's own living docs (CLAUDE.md) and
checking a few freshness signals on disk. Deliberately NOT a fresh LLM
analysis each run (a considered tradeoff): fast, free, no API cost, and
only ever as current as CLAUDE.md itself — which the existing daily
vault-sync job and normal work already keep up to date.

Two modes, same underlying data:
  --mode morning (default) — "due today" freshness flags + work queue +
    recent findings, framed as what to do today. Invoked by
    com.tradingbotapp.dailydigest.plist at 07:30 local.
  --mode evening — today's actual activity (journal events, new research
    notes, new trade reflections, all since midnight) + the same
    freshness flags as a heads-up for tomorrow, framed as a recap.
    Invoked by com.tradingbotapp.dailydigestevening.plist at 20:00 local.

Sends, via TelegramBot/notify.py, either way:
  - due-today / freshness flags: research-refresh cadence (weekly, per
    README), whether trade_journal.csv has seen recent activity, whether
    graded_calls.csv has real (non-pending) grades worth reading yet
  - (evening only) what actually happened today: journal event counts,
    new research notes logged today, new trade reflections today
  - a condensed version of CLAUDE.md's "Work queue for Claude Code"
    section (top-level numbered items only, not the full sub-bullet detail)
  - a condensed version of CLAUDE.md's "Empirical findings so far" section

Safe to run manually any time: ./daily_digest.sh [morning|evening]
"""
import argparse
import csv
import re
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent
sys.path.insert(0, str(ROOT / "TelegramBot"))
from notify import send_telegram  # noqa: E402

CLAUDE_MD = ROOT / "CLAUDE.md"
RESEARCH_LOG_DIR = ROOT / "research_log"
JOURNAL_FILE = ROOT / "trade_journal.csv"
GRADED_CALLS_FILE = ROOT / "graded_calls.csv"
REFLECTIONS_DIR = ROOT / "trade_reflections"
RESEARCH_CADENCE_DAYS = 7
NOTE_PATTERN = re.compile(r"^([A-Z0-9=.\-^]+)_(\d{4}-\d{2}-\d{2})_\d{4}\.md$")


def extract_section(text: str, header_prefix: str) -> str:
    pattern = rf"^##\s+{re.escape(header_prefix)}.*?\n(.*?)(?=\n##\s|\Z)"
    m = re.search(pattern, text, re.DOTALL | re.MULTILINE)
    return m.group(1).strip() if m else ""


def top_level_items(section_text: str, max_items: int = 6, max_len: int = 170) -> list:
    items = []
    for line in section_text.splitlines():
        stripped = line.strip()
        if re.match(r"^\d+\.\s", stripped):
            items.append(stripped[:max_len] + ("..." if len(stripped) > max_len else ""))
        if len(items) >= max_items:
            break
    return items


def bullet_items(section_text: str, max_items: int = 5, max_len: int = 160) -> list:
    items = []
    for line in section_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("- "):
            items.append(stripped[:max_len] + ("..." if len(stripped) > max_len else ""))
        if len(items) >= max_items:
            break
    return items


def research_freshness() -> str:
    notes = list(RESEARCH_LOG_DIR.glob("*.md")) if RESEARCH_LOG_DIR.exists() else []
    if not notes:
        return "No research notes yet — run run_research_agent_watchlist.sh"
    latest = max(n.stat().st_mtime for n in notes)
    days = (datetime.now().timestamp() - latest) / 86400
    if days >= RESEARCH_CADENCE_DAYS:
        return (f"⚠️ OVERDUE — last run {days:.0f}d ago (cadence {RESEARCH_CADENCE_DAYS}d). "
                f"Run run_research_agent_watchlist.sh today.")
    return f"OK — last run {days:.0f}d ago, due again in {RESEARCH_CADENCE_DAYS - days:.0f}d."


def journal_freshness() -> str:
    if not JOURNAL_FILE.exists():
        return "No trade_journal.csv yet."
    try:
        with open(JOURNAL_FILE) as f:
            rows = list(csv.reader(f))
        if len(rows) < 2:
            return "trade_journal.csv exists but has no entries yet."
        # The newest EVENT, not the last line written. Reconstruction and
        # correction rows (CLOSE_RECONSTRUCTED, RESULT_CORRECTED, NOTE) are
        # appended later but carry the timestamp of the event they describe,
        # so the file is not sorted by time and rows[-1] can be months old.
        stamps = []
        for r in rows[1:]:
            try:
                stamps.append(datetime.fromisoformat(r[0]))
            except (ValueError, IndexError):
                continue
        if not stamps:
            return "trade_journal.csv exists but has no readable timestamps."
        last_dt = max(stamps)
        last_ts = last_dt.isoformat(timespec="seconds")
        days = (datetime.now() - last_dt).total_seconds() / 86400
        return f"Last journal entry {days:.1f}d ago ({last_ts})."
    except Exception as e:
        return f"Could not read trade_journal.csv ({e})."


def grading_status() -> str:
    if not GRADED_CALLS_FILE.exists():
        return "graded_calls.csv doesn't exist yet — run grade_calls.py --csv once notes are >=5 days old."
    try:
        with open(GRADED_CALLS_FILE) as f:
            rows = list(csv.DictReader(f))
        if not rows:
            return "graded_calls.csv is empty."
        graded = [r for r in rows if r.get("correct") not in (None, "", "None")]
        pending = len(rows) - len(graded)
        return f"{len(graded)} graded, {pending} pending — worth a look: python3 grade_calls.py"
    except Exception as e:
        return f"Could not read graded_calls.csv ({e})."


def todays_activity() -> list:
    """Evening-only: what actually happened today, not just freshness."""
    today = datetime.now().date()
    lines = []

    if JOURNAL_FILE.exists():
        try:
            with open(JOURNAL_FILE) as f:
                rows = list(csv.DictReader(f))
            todays_rows = [r for r in rows
                           if datetime.fromisoformat(r["timestamp"]).date() == today]
            if todays_rows:
                by_event = {}
                for r in todays_rows:
                    by_event[r["event"]] = by_event.get(r["event"], 0) + 1
                counts = ", ".join(f"{v} {k}" for k, v in sorted(by_event.items()))
                lines.append(f"• Trade journal: {len(todays_rows)} entries today ({counts})")
                blocked = [r for r in todays_rows if r["event"] == "BLOCKED"]
                if blocked:
                    lines.append(f"  ⚠️ {len(blocked)} order(s) blocked by RiskGuard today")
            else:
                lines.append("• Trade journal: no activity today")
        except Exception as e:
            lines.append(f"• Trade journal: couldn't read today's activity ({e})")

    if RESEARCH_LOG_DIR.exists():
        todays_tickers = set()
        for n in RESEARCH_LOG_DIR.glob("*.md"):
            if datetime.fromtimestamp(n.stat().st_mtime).date() == today:
                m = NOTE_PATTERN.match(n.name)
                if m:
                    todays_tickers.add(m.group(1))
        if todays_tickers:
            lines.append(f"• Research notes logged today: {', '.join(sorted(todays_tickers))}")
        else:
            lines.append("• Research notes logged today: none")

    if REFLECTIONS_DIR.exists():
        todays_refl = [p for p in REFLECTIONS_DIR.glob("*.md")
                       if datetime.fromtimestamp(p.stat().st_mtime).date() == today]
        if todays_refl:
            lines.append(f"• Trade reflections written today: {len(todays_refl)}")

    return lines


def build_message(mode: str) -> str:
    today = datetime.now().strftime("%Y-%m-%d (%A)")
    if not CLAUDE_MD.exists():
        noun = "plan" if mode == "morning" else "recap"
        return f"Daily digest: CLAUDE.md not found, can't build today's {noun}."

    text = CLAUDE_MD.read_text()
    queue_items = top_level_items(extract_section(text, "Work queue for Claude Code"))
    findings_items = bullet_items(extract_section(text, "Empirical findings so far"))

    parts = []
    if mode == "morning":
        parts.append(f"☀️ Good morning — TradingBotApp plan for {today}")
    else:
        parts.append(f"🌙 Evening recap — TradingBotApp — {today}")
    parts.append("")

    if mode == "evening":
        parts.append("📋 Today's activity:")
        activity = todays_activity()
        parts.extend(activity if activity else ["• Nothing logged today"])
        parts.append("")

    parts.append("📌 Due today / freshness checks:" if mode == "morning"
                 else "📌 Freshness checks (heads-up for tomorrow):")
    parts.append(f"• Research agent: {research_freshness()}")
    parts.append(f"• Paper trading: {journal_freshness()}")
    parts.append(f"• Call grading: {grading_status()}")
    parts.append("")

    if queue_items:
        parts.append("🔧 Work queue (from CLAUDE.md):")
        parts.extend(queue_items)
        parts.append("")

    if findings_items:
        parts.append("📈 Recent findings to keep in mind:")
        parts.extend(findings_items)
        parts.append("")

    parts.append("Full detail: CLAUDE.md")
    return "\n".join(parts)


def main() -> None:
    ap = argparse.ArgumentParser(description="Send the morning plan or evening recap digest.")
    ap.add_argument("mode", nargs="?", default="morning", choices=["morning", "evening"])
    args = ap.parse_args()

    message = build_message(args.mode)
    send_telegram(message)
    print(message)


if __name__ == "__main__":
    main()
